language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
sudo: false
install:
  - pip install -U pip setuptools zc.buildout
  - buildout 
script: ./bin/test
