language: python
sudo: false

python:
  #- "2.4"
  #- "2.5"
  #- "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"  # PyPy2 2.5.0
  - "pypy-5.3.1"

install:
    python setup.py install

script: python -m unittest odict.tests
